### ISSUE TITLE
拟定修改Caffe的思路和计划

### ISSUE THREAD

**Issue by ACA-Lab-SJTU** [acada-sjtu/ReRAM2019#5]

**Comment by ACA-Lab-SJTU** [comment]
已完成剪枝部分的实现；
探索量化部分的实现。

**Comment by cqchu** [comment]
量化部分的思路:
训练 - 用浮点数
    ParamSpec中应该新增bitwidth变量控制每层量化的宽度, 网络初始化过程中应新增一个GetQuantBasis()函数, 利用此bitwidth以及初始的权值, 求取量化的level
    在ADMM过程中根据量化要求实现EuclidProj()函数, 具体应该是把Z中靠近Quant-level的值置位为对应Quant-Level
    retrain, 把经过ADMM过程的权值迭代置位为定点数, 得到量化的权值
Inference - 定点数
    activation的处理: 根据数据集统计浮点情况下每一层的activation的范围, 计算一个预知的Quant-level, 把inference时每一层的计算结果cast到Quant-Level上
    修改对应的Layer中的Forward函数, 其基本计算模型是: S_o*Q_o = S_i*S_w*sum(Q_i*Q_w)

候选方案: 如果上述方案效果不理想, 把Activation的Quant-Level(S_o)的也加入训练过程, 即前向时也使用定点数计算loss, 反向时则使用浮点数
