### ISSUE TITLE
框架中添加对于ADMM算法的支持

### ISSUE THREAD

**Issue by cqchu** [acada-sjtu/ReRAM2019#8]
预计完成时间：4月19日(周五)
内容：
1. 在SGDSolver的Regular函数中添加ADMM正则项
2. 在SGD算法中实现ADMM算法

验证：
1. 利用leNet+Mnist跑通整个流程，查看生成的模型中的三种结构性稀疏的存在性
2. 跑Cifar10+ResNet18得到一个Naive的结果

**Comment by cqchu** [comment]
已得到初步结果，在Cifar10 + Resnet18上：
128x128：压缩26.63x
576x128：压缩11.77x
256x256：压缩15.25x

**Comment by ACA-Lab-SJTU** [comment]
很好

-
Li Jiang, Ph.D., Associate Professor,
Department of computer science and engineering,
Shanghai Jiao Tong University
